const API="/api"; let token=localStorage.getItem("token"); let current=null;
async function api(path,opts={}){opts.headers={...(opts.headers||{}),...(token?{Authorization:"Bearer "+token}:{})}; if(opts.body && typeof opts.body==="object"){opts.headers["Content-Type"]="application/json";opts.body=JSON.stringify(opts.body)} const r=await fetch(API+path,opts); const d=await r.json().catch(()=>({})); if(!r.ok) throw Error(d.detail||"Erro"); return d}
function openAuth(){document.getElementById("modal").classList.remove("hidden");renderAuth("login")}
function closeAuth(){document.getElementById("modal").classList.add("hidden")}
function renderAuth(mode){document.getElementById("modalContent").innerHTML=mode==="login"?`<h2>Entrar</h2><form onsubmit="login(event)"><input id="email" type="email" placeholder="E-mail" required><input id="password" type="password" placeholder="Senha" required><button>Entrar</button></form><p>Não tem conta? <a href="#" onclick="renderAuth('register')">Cadastre-se</a></p>`:`<h2>Criar conta</h2><form onsubmit="register(event)"><input id="name" placeholder="Nome" required><input id="email" type="email" placeholder="E-mail" required><input id="password" type="password" placeholder="Senha (6+ caracteres)" required><button>Cadastrar</button></form><p>Já tem conta? <a href="#" onclick="renderAuth('login')">Entrar</a></p>`}
async function login(e){e.preventDefault();try{const d=await api("/auth/login",{method:"POST",body:{email:email.value,password:password.value}});token=d.access_token;localStorage.setItem("token",token);closeAuth();load()}catch(x){alert(x.message)}}
async function register(e){e.preventDefault();try{await api("/auth/register",{method:"POST",body:{name:name.value,email:email.value,password:password.value}});alert("Conta criada!");renderAuth("login")}catch(x){alert(x.message)}}
async function load(){const courses=await api("/courses");document.getElementById("courses").innerHTML=courses.map(c=>`<article class="card"><img src="${c.image||'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80'}"><div class="card-body"><h3>${c.title}</h3><p>${c.description}</p><div class="meta">${c.lessons} aulas • ${c.price?"Pago":"Grátis"}</div><button onclick="enroll(${c.id})">Começar curso</button></div></article>`).join("");if(token){try{current=await api("/me");document.getElementById("authBtn").textContent="Sair";document.getElementById("authBtn").onclick=logout;const mine=await api("/my-courses");document.getElementById("myCourses").innerHTML=mine.length?mine.map(x=>`<div><strong>${x.title}</strong><p>Matriculado ✓</p></div>`).join(""):"<p>Você ainda não está matriculado em nenhum curso.</p>"}catch{logout()}}}
async function enroll(id){if(!token){openAuth();return}try{await api(`/courses/${id}/enroll`,{method:"POST"});alert("Matrícula realizada!");load()}catch(x){alert(x.message)}}
function logout(){token=null;localStorage.removeItem("token");location.reload()}
load();
