const API="/api"; let token=localStorage.getItem("token");
const money=n=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:"Bearer "+token}:{})}; if(opt.body&&typeof opt.body!=="string"){opt.headers["Content-Type"]="application/json";opt.body=JSON.stringify(opt.body)};let r=await fetch(API+url,opt);let d=await r.json();if(!r.ok)throw Error(d.detail||"Erro");return d}
async function loadCategories(){let c=await api("/categories");document.querySelector("#category").innerHTML='<option value="">Todas as categorias</option>'+c.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}
async function loadProducts(){let s=document.querySelector("#search").value,c=document.querySelector("#category").value;let ps=await api("/products?search="+encodeURIComponent(s)+(c?"&category_id="+c:""));document.querySelector("#products").innerHTML=ps.map(p=>`<article class="card"><img src="${p.image_url||'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800'}"><div class="card-body"><h3>${p.name}</h3><p>${p.description}</p><div>${p.sale_price?`<span class="old">${money(p.price)}</span>`:""}<span class="price">${money(p.sale_price??p.price)}</span></div><small>${p.stock} em estoque</small><button onclick="addCart(${p.id})">Adicionar ao carrinho</button></div></article>`).join("")}
async function addCart(id){if(!token)return openLogin();try{await api("/cart/items",{method:"POST",body:{product_id:id,quantity:1}});alert("Produto adicionado ao carrinho!");updateCartCount()}catch(e){alert(e.message)}}
async function updateCartCount(){if(!token)return;try{let c=await api("/cart");document.querySelector("#cartCount").textContent=c.items.reduce((a,x)=>a+x.quantity,0)}catch{}}
function openLogin(){document.querySelector("#modal").classList.remove("hidden");document.querySelector("#modal").innerHTML=`<div class="panel"><h2>Entrar</h2><input id="email" placeholder="E-mail"><input id="pass" type="password" placeholder="Senha"><button onclick="login()">Entrar</button><button onclick="register()">Criar conta</button><button onclick="closeModal()">Fechar</button><p id="msg"></p></div>`}
function closeModal(){document.querySelector("#modal").classList.add("hidden")}
async function login(){try{let d=await api("/auth/login",{method:"POST",body:{email:email.value,password:pass.value}});token=d.token;localStorage.setItem("token",token);closeModal();updateCartCount()}catch(e){msg.textContent=e.message}}
async function register(){let n=prompt("Seu nome:");if(!n)return;try{let d=await api("/auth/register",{method:"POST",body:{name:n,email:email.value,password:pass.value}});token=d.token;localStorage.setItem("token",token);closeModal()}catch(e){msg.textContent=e.message}}
async function loadCart(){if(!token)return openLogin();let c=await api("/cart");document.querySelector("#modal").classList.remove("hidden");document.querySelector("#modal").innerHTML=`<div class="panel"><h2>Seu carrinho</h2>${c.items.length?c.items.map(i=>`<p><b>${i.product.name}</b> × ${i.quantity} — ${money(i.subtotal)} <button onclick="removeCart(${i.id})">×</button></p>`).join(""):"<p>Seu carrinho está vazio.</p>"}<h3>Total: ${money(c.total)}</h3><textarea id="address" placeholder="Endereço de entrega"></textarea><button onclick="checkout()">Finalizar pedido</button><button onclick="closeModal()">Fechar</button></div>`}
async function removeCart(id){await api("/cart/items/"+id,{method:"DELETE"});loadCart();updateCartCount()}
async function checkout(){try{let d=await api("/orders",{method:"POST",body:{address:document.querySelector("#address").value}});alert("Pedido #"+d.id+" criado!");closeModal();updateCartCount()}catch(e){alert(e.message)}}
loadCategories();loadProducts();updateCartCount();